logging:
  level:
    com.example.springsecuritydemo: DEBUG
spring:
  security:
    filter:
      order: -100 # Set a high order to ensure this filter runs last
    persist:
      # Disable SecurityContext persistence
      security-context: false
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect

app:
  jwtSecret: 1a2b3c4dH(@$HG*)JGKL:LG:J_+G$@}O{{WOB|@$_(B@|\\b@$|jH()@$H)HONGJN"G$@"FJI;:0fJ:G@$JIjg90hHG*)@$H)GIFMVNBH$H@)G@$G)F)N@OK$GMIHG*)H@$*)G)*WDNVWDNOVL!N)G$@)*GH
  jwtExpirationInMs: 5000
  refreshExpirationInMs: 10000
